# Watch API 配置
api_config:
  WATCH_FRIEND_INFO_URL: https://watch.okii.com/watchfriend/watchinfo/int4Boolean?uuid=0
  LIKE_DETAIL_URL: https://api.watch.okii.com/social-service/personalInfo/getLikeDetailPage?uuid=0
  GET_WATCH_INIT_INFO_URL: http://points.tiancaixing.com/operation/accountScore/getWatchInitInfo/{watchid}/{model}?uuid=0
  ADD_FRIEND_URL: https://watch.okii.com/watchfriend/group/audit?uuid=0
  CREATE_URL: https://watch.okii.com/interphone/create?uuid=0
  SPORT_LINK_URL: https://moment.watch.okii.com/moment/public?uuid=0
  LIKE_URL: https://api.watch.okii.com/social-service/personalInfo/like?uuid=0
  GETFRIEND_URL: https://watch.okii.com/smartwatch/geniusAccount/watchGetInfo?uuid=0
  UPDATE_NAME_URL: https://watch.okii.com/smartwatch/watchaccount/updateBabyName?uuid=0
  MOMENT_SEARCH_URL: https://moment.watch.okii.com/moment/search?uuid=0
  STEP_URL: https://sport.watch.okii.com/sportweather/sport/i6?uuid=0
  SPORT_URL: https://sport.watch.okii.com/sport-service/sport/i25/uploadWatchSportRecord?uuid=0
  PERSONSIGN_URL: https://api.watch.okii.com/social-service/personalInfo/updateSignature?uuid=0
  CHANGE_URL: https://watch.okii.com/watchaccount/bindnumber?uuid=0
  UPLOAD_DOMAIN: http://upload.qiniup.com
  GET_PERSONAL_INFO_URL: https://api.watch.okii.com/social-service/personalInfo/getPersonalInfoUnite?uuid=0
  APP_SEARCH_URL: https://api.watch.okii.com/appstore/search/result?uuid=0
  UPDATE_REALNAME_URL: https://watch.okii.com/smartwatch/watchaccount/updateRealName?uuid=0
# MySQL 配置
mysql_config:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "password"
  database: "xtcsql"